[package]
name = "upscaler"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.21.0", features = ["wgpu", "cuda", "ndarray", "autodiff"] }
image = "0.25.10"
thiserror = "2.0.12"
rand = "0.8"

[[bin]]
name = "upscaler"
path = "src/main.rs"

[[bin]]
name = "train"
path = "src/bin/train.rs"

[[bin]]
name = "test_checkpoints"
path = "src/bin/test_checkpoints.rs"
